import { Providers } from "@/app/providers";
import { Box } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import MainContent from "./componets/MainContent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JUC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <>
        <Box as="body" bg="#06142E">
          <Providers>
            <MainContent>{children}</MainContent>
          </Providers>
        </Box>
      </>
    </html>
  );
}
